import type { Metadata } from "next";
import "./globals.css";
import AppWrapper from "@/components/AppWrapper";

export const metadata: Metadata = {
    title: "TaskNest",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`min-h-screen px-4`}>
                <AppWrapper>
                    <main className="">{children}</main>
                </AppWrapper>
            </body>
        </html>
    );
}
